project_id = "qcuiuubbaozcmejzvxje"

[functions.address-validation]
verify_jwt = false

[functions.calculate-service-fee]
verify_jwt = false

[functions.cleanup-expired-verification-codes]
verify_jwt = false

[functions.confirm-merchant-fee-profile]
verify_jwt = false

[functions.create-customer-merchant]
verify_jwt = false

[functions.create-finix-customer-payment-instrument]
verify_jwt = false

[functions.create-finix-customer]
verify_jwt = false

[functions.create-merchant-fee-profile]
verify_jwt = false

[functions.create-service-application-with-payment]
verify_jwt = false

[functions.create-tax-submission-with-payment]
verify_jwt = false

[functions.create-user-bank-account-tokenized]
verify_jwt = false

[functions.create-user-payment-card-tokenized]
verify_jwt = false

[functions.fetch-merchant-payout-profile]
verify_jwt = false

[functions.get-finix-config]
verify_jwt = false

[functions.get-google-pay-merchant-id]
verify_jwt = false

[functions.google-maps-proxy]
verify_jwt = false

[functions.process-apple-pay-transfer]
verify_jwt = false

[functions.process-finix-refund]
verify_jwt = false

[functions.process-finix-transfer]
verify_jwt = false

[functions.process-google-pay-transfer]
verify_jwt = false

[functions.process-unified-google-pay]
verify_jwt = false

[functions.process-unified-payment]
verify_jwt = false

[functions.send-bill-notification]
verify_jwt = false

[functions.send-contact-email]
verify_jwt = false

[functions.send-organization-invitation]
verify_jwt = false

[functions.send-unified-notification]
verify_jwt = false

[functions.send-verification]
verify_jwt = false

[functions.update-merchant-fee-profile]
verify_jwt = false

[functions.update-merchant-payout-profile]
verify_jwt = false

[functions.validate-apple-pay-merchant]
verify_jwt = false

[functions.verify-code]
verify_jwt = false
