project_id = "qcuiuubbaozcmejzvxje"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322

[db.pooler]
enabled = false
port = 54329
pool_mode = "transaction"
default_pool_size = 20
max_client_conn = 100

[realtime]
enabled = true
port = 54323
ip_version = "ipv4"

[studio]
enabled = true
port = 54323
api_url = "http://127.0.0.1:54321"

[inbucket]
enabled = true
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
enabled = true
port = 54325
file_size_limit = "50MiB"

[auth]
enabled = true
port = 54326
site_url = "http://127.0.0.1:3000"
additional_redirect_urls = ["https://127.0.0.1:3000"]
jwt_expiry = 3600
enable_refresh_token_rotation = true
refresh_token_reuse_interval = 10
enable_manual_linking = false

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = true

[edge_runtime]
enabled = true
port = 54327
ip_version = "ipv4"

[analytics]
enabled = false
port = 54328
vector_port = 54329
backend = "postgres"

[functions.address-validation]
verify_jwt = true

[functions.confirm-merchant-fee-profile]
verify_jwt = true

[functions.create-customer-merchant]
verify_jwt = true

[functions.create-finix-customer]
verify_jwt = true

[functions.create-finix-customer-payment-instrument]
verify_jwt = true

[functions.create-merchant-fee-profile]
verify_jwt = true

[functions.create-user-bank-account]
verify_jwt = true

[functions.create-user-payment-card]
verify_jwt = true

[functions.fetch-merchant-payout-profile]
verify_jwt = true

[functions.get-google-pay-merchant-id]
verify_jwt = true

[functions.google-maps-proxy]
verify_jwt = false

[functions.process-apple-pay-transfer]
verify_jwt = true

[functions.process-finix-transfer]
verify_jwt = true

[functions.process-google-pay-transfer]
verify_jwt = true

[functions.send-contact-email]
verify_jwt = false

[functions.send-organization-invitation]
verify_jwt = true

[functions.send-verification]
verify_jwt = false

[functions.update-merchant-fee-profile]
verify_jwt = true

[functions.update-merchant-payout-profile]
verify_jwt = true

[functions.validate-apple-pay-merchant]
verify_jwt = true